services:
  - type: web
    name: ludibot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
